# Generated by Django 4.2.6 on 2023-10-08 21:48

import asso.address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A short description for this content (not visible in views)",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Object ordering value",
                        verbose_name="Order",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A two letter code to identify country (based on ISO-3166)",
                        max_length=2,
                        unique=True,
                        validators=[asso.address.models.validate_uppercase],
                        verbose_name="Country Code (ISO-3166)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["order", "title"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="A short description for this content (not visible in views)",
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Object ordering value",
                        verbose_name="Order",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A two letter code to identify a state, region, province in a country",
                        max_length=2,
                        validators=[asso.address.models.validate_uppercase],
                        verbose_name="Region Code",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        help_text="The country this Region belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="address.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddConstraint(
            model_name="region",
            constraint=models.UniqueConstraint(
                fields=("code", "country"), name="unique_region_code_for_country"
            ),
        ),
    ]
