# Generated by Django 4.2.6 on 2023-10-08 18:37

import asso.address.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Object ordering value",
                        verbose_name="Order",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name to display in selector",
                        max_length=100,
                        verbose_name="Displayed name",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="A two letter code to identify a state, region, province inside a country",
                        max_length=2,
                        validators=[asso.address.models.validate_uppercase],
                        verbose_name="Region Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["order", "name"],
            },
        ),
    ]
