[build-system]
requires = ["setuptools", "wheel"]

[tool.setuptools.packages.find]
include = ["admin", "website"]

[project]
name = "asso-django"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "django>=4",
    "django-extensions",
    "django-jazzmin",
    "django-money",
    "django-relativedelta",
    "loguru",
    "Pillow",
    "python-dateutil",
    "python-decouple",
]

[project.optional-dependencies]
dev = ["black", "isort", "ipython"]
test = ["pytest"]

[tool.isort]
profile = "black"