# Generated by Django 4.2 on 2023-04-29 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0003_membershipperiod_price_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The User the Member use for Login",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
