# Generated by Django 4.2.7 on 2023-11-03 21:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="content",
            field=ckeditor.fields.RichTextField(default=""),
        ),
    ]
