# Generated by Django 4.2.1 on 2023-06-14 01:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("academy", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainer",
            options={},
        ),
        migrations.AddField(
            model_name="trainer",
            name="display_name",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Displayed name"
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                help_text="The User the Trainer use for Login",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddConstraint(
            model_name="trainer",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user__isnull", False),
                    ("display_name__length__gt", 0),
                    _connector="OR",
                ),
                name="not_both_null",
                violation_error_message="displayed name and user cannot be either unset",
            ),
        ),
    ]
