# Generated by Django 4.1.7 on 2023-03-15 01:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0002_alter_trainer_options_remove_trainer_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="session",
            options={"ordering": ["-creation_date"]},
        ),
        migrations.RemoveField(
            model_name="session",
            name="description",
        ),
        migrations.RemoveField(
            model_name="session",
            name="name",
        ),
        migrations.RemoveField(
            model_name="session",
            name="trash_state",
        ),
    ]
