# Generated by Django 4.2 on 2023-04-30 00:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0004_enrollment_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["-creation_date"]},
        ),
        migrations.RemoveField(
            model_name="event",
            name="description",
        ),
        migrations.RemoveField(
            model_name="event",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="subtitle",
            field=models.CharField(
                default="",
                help_text="Subtitle of the event",
                max_length=200,
                verbose_name="Subtitle",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title",
            field=models.CharField(
                default="",
                help_text="Title of the event",
                max_length=200,
                verbose_name="Title",
            ),
        ),
    ]
