# Generated by Django 4.2 on 2023-04-30 00:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0005_alter_event_options_remove_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
    ]
