# Generated by Django 4.2 on 2023-04-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0007_alter_event_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=100),
        ),
    ]
