# Generated by Django 4.2 on 2023-05-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0009_alter_event_subtitle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
