# Generated by Django 4.2.1 on 2023-05-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0010_alter_event_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Set this value if you dont want to set sessions",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Set this value if you dont want to set sessions",
                null=True,
            ),
        ),
    ]
