# Generated by Django 4.1.7 on 2023-03-15 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("website", "0005_alter_member_options_member_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created the object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who edited the object last time",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
    ]
