# Generated by Django 4.2.1 on 2023-05-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0011_sociallink_alter_navbaritem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navbaritem",
            name="url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
