# Generated by Django 4.2.5 on 2023-10-04 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociallink",
            name="logo",
            field=models.CharField(
                choices=[
                    ("globe", "Web site (default)"),
                    ("facebook", "Facebook"),
                    ("twitter", "Twitter"),
                    ("x", "X"),
                    ("linkedin", "LinkedIn"),
                    ("youtube", "YouTube"),
                    ("github", "GitHub"),
                    ("instagram", "Instagram"),
                ],
                default="globe",
                max_length=24,
                verbose_name="Logo Icon",
            ),
        ),
    ]
