# Generated by Django 4.1.3 on 2022-11-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0002_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="payment_date",
            field=models.DateField(null=True),
        ),
    ]
