# Generated by Django 4.1.7 on 2023-03-07 01:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_alter_membership_payment_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="member",
            old_name="name",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="surname",
            new_name="last_name",
        ),
    ]
