# Generated by Django 4.2 on 2023-04-21 00:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0006_alter_member_created_by_alter_member_updated_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="membership",
            name="member",
        ),
        migrations.DeleteModel(
            name="Member",
        ),
        migrations.DeleteModel(
            name="Membership",
        ),
    ]
