# Generated by Django 4.2 on 2023-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("website", "0007_remove_membership_member_delete_member_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(blank=True, max_length=50)),
                ("url", models.CharField(blank=True, max_length=200, null=True)),
                ("active", models.BooleanField(default=True)),
                ("order", models.SmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
