# Generated by Django 4.2 on 2023-05-08 14:50

from django.db import migrations, models

import asso.core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0008_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", asso.core.fields.UniqueBooleanField(default=False)),
                ("brand", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["active"],
            },
        ),
    ]
