# Generated by Django 4.2.1 on 2023-05-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0009_themeconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="themeconfig",
            options={"ordering": ["-active"]},
        ),
        migrations.AddField(
            model_name="themeconfig",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos"),
        ),
    ]
