# Generated by Django 4.2.1 on 2023-05-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0010_alter_themeconfig_options_themeconfig_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Used for object ordering",
                        verbose_name="Order",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("url", models.URLField()),
                (
                    "logo",
                    models.SlugField(
                        help_text=(
                            "One of the logo-* icons on https://ionic.io/ionicons "
                            "(facebook, twitter, linkedin, youtube, ...)"
                        ),
                        verbose_name="Logo Icon",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Used for object ordering", verbose_name="Order"
            ),
        ),
    ]
