# Generated by Django 4.2.1 on 2023-05-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0012_alter_navbaritem_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sociallink",
            options={"ordering": ["title"]},
        ),
        migrations.AddField(
            model_name="sociallink",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="%(class) description",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="navbaritem",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Object ordering value", verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Object ordering value", verbose_name="Order"
            ),
        ),
        migrations.AlterField(
            model_name="sociallink",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
    ]
