# Generated by Django 4.2.2 on 2023-06-19 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accountant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="transaction",
            field=models.OneToOneField(
                help_text="Indicate the Transaction of the Purchase",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_purchase",
                to="accountant.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="liberaloffer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="liberaloffer",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="liberaloffer",
            name="transaction",
            field=models.OneToOneField(
                help_text="Indicate the Transaction of the LiberalOffer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_liberal_offer",
                to="accountant.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="invoice",
            field=models.ForeignKey(
                help_text="Indicate the Invoice of ownership",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_rows",
                to="accountant.invoice",
                verbose_name="Invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoicerow",
            name="transaction",
            field=models.OneToOneField(
                help_text="Indicate the Transaction of the row",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction_invoice_rows",
                to="accountant.transaction",
                verbose_name="Transaction",
            ),
        ),
        migrations.AddField(
            model_name="invoicedirection",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="invoicedirection",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="direction",
            field=models.ForeignKey(
                help_text="Indicate the direction of the Invoice",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_direction_invoices",
                to="accountant.invoicedirection",
                verbose_name="Direction",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="analytictag",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="analytictag",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="analytictag",
            name="parent",
            field=models.ForeignKey(
                help_text="The parent tag of this AnalyticTag",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytic_tag_children",
                to="accountant.analytictag",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this object",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("invoice_number", "year"), name="unique_invoice_code"
            ),
        ),
    ]
