# Generated by Django 4.1.7 on 2023-03-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="trainer",
            options={"ordering": ["-creation_date"]},
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="description",
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="name",
        ),
        migrations.AddField(
            model_name="trainer",
            name="biography",
            field=models.TextField(
                blank=True, help_text="Trainer Biography", verbose_name="Biography"
            ),
        ),
    ]
