# Generated by Django 4.2 on 2023-04-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("academy", "0006_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="subtitle",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Subtitle of the event",
                max_length=200,
                verbose_name="Subtitle",
            ),
        ),
    ]
