# Generated by Django 4.2 on 2023-04-21 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="",
                        help_text="Object name",
                        max_length=256,
                        verbose_name="Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Object description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The Date and the Time of creation on the object",
                        verbose_name="Creation Date and Time",
                    ),
                ),
                (
                    "edit_date",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The Date and the Time of last time the object was edited",
                        verbose_name="Last edit Date and Time",
                    ),
                ),
                (
                    "trash_state",
                    models.BooleanField(
                        default=False,
                        help_text="Indicates if the object is trashed",
                        verbose_name="Trashed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The User who has created the object",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creation User",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        help_text="The Period the Membership Apply",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_member_registration",
                        to="membership.membershipperiod",
                        verbose_name="Period",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The User who edited the object last time",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last edit User",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="registerentry",
            name="rester",
            field=models.ForeignKey(
                help_text="The owner Register",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="register_entries",
                to="membership.memberregister",
                verbose_name="Register",
            ),
        ),
        migrations.DeleteModel(
            name="MembersRegister",
        ),
    ]
