# Generated by Django 4.2.2 on 2023-06-21 00:52

import asso.core.utils
from django.db import migrations, models
import relativedeltafield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"verbose_name": "Member", "verbose_name_plural": "Members"},
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="duration",
            field=relativedeltafield.fields.RelativeDeltaField(
                default=asso.core.utils.yearly_duration,
                help_text="Duration of this Period (as ISO8601 format with designators",
                verbose_name="Duration",
            ),
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="start_date",
            field=models.DateField(
                default=asso.core.utils.year_first_day,
                help_text="Initial day of the Membership period",
                verbose_name="Start Date",
            ),
        ),
    ]
