# Generated by Django 4.2.1 on 2023-05-29 23:34

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="first_name",
            field=models.CharField(
                default="[INVALID]", max_length=150, verbose_name="first name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="last_name",
            field=models.CharField(
                default="[INVALID]", max_length=150, verbose_name="last name"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="sex",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                max_length=1,
                verbose_name="Gender (M/F)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="member",
            name="cf",
            field=models.CharField(
                help_text="Codice Fiscale",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Z0-9]{16}", "Invalid Fiscal Code"
                    )
                ],
                verbose_name="Codice Fiscale",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                help_text="The User used for Login",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
