# Generated by Django 4.2.2 on 2023-06-21 00:57

import asso.core.utils
from django.db import migrations
import relativedeltafield.fields


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0002_alter_member_options_alter_membershipperiod_duration_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="membershipperiod",
            name="duration",
            field=relativedeltafield.fields.RelativeDeltaField(
                default=asso.core.utils.yearly_duration,
                help_text="Duration of this Period (as ISO8601 format with designators)",
                verbose_name="Duration",
            ),
        ),
    ]
