# Generated by Django 4.2.5 on 2023-10-02 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0004_alter_membershipperiod_price_currency"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberQualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "title",
                    models.CharField(default="", max_length=200, verbose_name="Title"),
                ),
            ],
            options={
                "ordering": ["slug"],
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="member",
            name="qualification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="members",
                to="membership.memberqualification",
                verbose_name="Study Degree",
            ),
        ),
    ]
