# Generated by Django 4.2.1 on 2023-06-05 16:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0005_remove_member_birth_provence_member_birth_province_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="phone",
            field=models.CharField(
                default="000 0000000",
                help_text="Phone Number",
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(00|\\+)?((\\d+|\\(\\d+\\))[ \\-]?)+\\d$",
                        "Use only plus sign (at start), dashes (-), spaces and parenthesis",
                    )
                ],
                verbose_name="Phone Number",
            ),
            preserve_default=False,
        ),
    ]
