# Generated by Django 4.2.5 on 2023-10-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_memberqualification_alter_member_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberqualification",
            name="order",
            field=models.SmallIntegerField(
                default=0, help_text="Object ordering value", verbose_name="Order"
            ),
        ),
    ]
