# Generated by Django 4.2 on 2023-05-01 15:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0005_alter_member_cf_alter_member_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="email",
        ),
        migrations.RemoveField(
            model_name="member",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="member",
            name="last_name",
        ),
    ]
