# Generated by Django 4.2.1 on 2023-05-25 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0006_remove_member_email_remove_member_first_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["-edit_date"]},
        ),
        migrations.AlterModelOptions(
            name="memberregister",
            options={"ordering": ["-creation_date"]},
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"ordering": ["-edit_date"]},
        ),
        migrations.AlterModelOptions(
            name="membershipperiod",
            options={"ordering": ["-creation_date"]},
        ),
        migrations.AlterModelOptions(
            name="registerentry",
            options={"ordering": ["-edit_date"]},
        ),
        migrations.RemoveField(
            model_name="member",
            name="trash_state",
        ),
        migrations.RemoveField(
            model_name="member",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="memberregister",
            name="name",
        ),
        migrations.RemoveField(
            model_name="memberregister",
            name="trash_state",
        ),
        migrations.RemoveField(
            model_name="memberregister",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="trash_state",
        ),
        migrations.RemoveField(
            model_name="membership",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="membershipperiod",
            name="name",
        ),
        migrations.RemoveField(
            model_name="membershipperiod",
            name="trash_state",
        ),
        migrations.RemoveField(
            model_name="membershipperiod",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="registerentry",
            name="trash_state",
        ),
        migrations.RemoveField(
            model_name="registerentry",
            name="updated_by",
        ),
        migrations.AddField(
            model_name="member",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_trashed",
            field=models.BooleanField(
                default=False, help_text="Is the object trashed", verbose_name="Trashed"
            ),
        ),
        migrations.AddField(
            model_name="memberregister",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="memberregister",
            name="is_trashed",
            field=models.BooleanField(
                default=False, help_text="Is the object trashed", verbose_name="Trashed"
            ),
        ),
        migrations.AddField(
            model_name="memberregister",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="membership",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="is_trashed",
            field=models.BooleanField(
                default=False, help_text="Is the object trashed", verbose_name="Trashed"
            ),
        ),
        migrations.AddField(
            model_name="membershipperiod",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="membershipperiod",
            name="is_trashed",
            field=models.BooleanField(
                default=False, help_text="Is the object trashed", verbose_name="Trashed"
            ),
        ),
        migrations.AddField(
            model_name="membershipperiod",
            name="title",
            field=models.CharField(default="", max_length=256, verbose_name="Title"),
        ),
        migrations.AddField(
            model_name="registerentry",
            name="edit_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who last edited this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Last edit User",
            ),
        ),
        migrations.AddField(
            model_name="registerentry",
            name="is_trashed",
            field=models.BooleanField(
                default=False, help_text="Is the object trashed", verbose_name="Trashed"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and Time of %(class)'s creation",
                verbose_name="Creation Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and Time of object's last edit",
                verbose_name="Last edit Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="memberregister",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="memberregister",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and Time of %(class)'s creation",
                verbose_name="Creation Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="memberregister",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="%(class) description",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="memberregister",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and Time of object's last edit",
                verbose_name="Last edit Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and Time of %(class)'s creation",
                verbose_name="Creation Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and Time of object's last edit",
                verbose_name="Last edit Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and Time of %(class)'s creation",
                verbose_name="Creation Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="%(class) description",
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="membershipperiod",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and Time of object's last edit",
                verbose_name="Last edit Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="registerentry",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="The User who has created this %(class)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_created_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creation User",
            ),
        ),
        migrations.AlterField(
            model_name="registerentry",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date and Time of %(class)'s creation",
                verbose_name="Creation Date and Time",
            ),
        ),
        migrations.AlterField(
            model_name="registerentry",
            name="edit_date",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and Time of object's last edit",
                verbose_name="Last edit Date and Time",
            ),
        ),
    ]
