# Generated by Django 4.2.1 on 2023-06-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0007_member_address_additional_member_address_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="notes",
            field=models.TextField(
                blank=True, default="", verbose_name="Internal Notes"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="privacy_acknowledgement",
            field=models.DateField(
                blank=True,
                default=None,
                help_text="Last date Member has read privacy page",
                null=True,
                verbose_name="Privacy Page Aknowledgement",
            ),
        ),
    ]
