# Generated by Django 4.2.1 on 2023-06-05 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0008_member_notes_member_privacy_acknowledgement"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="document_expires",
            field=models.DateField(
                default=datetime.date(1970, 1, 1),
                verbose_name="Document Expiration Date",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="document_grant_from",
            field=models.CharField(
                default="INVALID",
                help_text="Public Authority who grant you the document",
                max_length=100,
                verbose_name="Who has grant the Document",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="document_number",
            field=models.CharField(
                default="INVALID", max_length=30, verbose_name="Document Number/Code"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("carta-identita", "Carta Identità"),
                    ("passaporto", "Passaporto"),
                    ("patente", "Patente"),
                ],
                default="carta-identita",
                max_length=16,
                verbose_name="Document Type",
            ),
            preserve_default=False,
        ),
    ]
