# Generated by Django 4.2.1 on 2023-06-05 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "membership",
            "0009_member_document_expires_member_document_grant_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="profession",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="qualification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("None", "Default"),
                    ("master", "Master Universitario"),
                    ("phd", "Dottorato di Ricerca"),
                    ("master-degree", "Laurea Magistrale"),
                    ("bachelor-degree", "Laurea"),
                    ("high-school", "Diploma Maturità"),
                    ("mid-school", "Licenza Media"),
                    ("primary_school", "Elementari"),
                ],
                default=None,
                max_length=16,
                null=True,
                verbose_name="Study Degree",
            ),
        ),
    ]
