# Generated by Django 4.2.1 on 2023-06-06 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0010_member_profession_member_qualification"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="come_from",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="How you found us"
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="interests",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="Interests"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="profession",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Profession"
            ),
        ),
    ]
