# Generated by Django 4.2.1 on 2023-06-07 12:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0012_alter_member_document_expires_alter_member_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registerentry",
            old_name="rester",
            new_name="register",
        ),
        migrations.AlterField(
            model_name="member",
            name="birth_date",
            field=models.DateField(verbose_name="Birth Date"),
        ),
        migrations.AlterField(
            model_name="member",
            name="cf",
            field=models.CharField(
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "[A-Z0-9]{16}", "Invalid Fiscal Code"
                    )
                ],
                verbose_name="Codice Fiscale",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="member_memberships",
                to="membership.member",
                verbose_name="Member",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_memberships",
                to="membership.membershipperiod",
                verbose_name="Membership Period",
            ),
        ),
    ]
