# Generated by Django 4.2.2 on 2023-06-19 22:56

import asso.membership.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0015_alter_membershipperiod_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="cf",
            field=models.CharField(
                max_length=16,
                validators=[asso.membership.models.check_member_cf],
                verbose_name="Codice Fiscale",
            ),
        ),
    ]
