# Generated by Django 4.2.2 on 2023-06-19 23:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("membership", "0016_alter_member_cf"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="address_number",
        ),
    ]
