# Generated by Django 4.2.2 on 2023-06-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("membership", "0017_remove_member_address_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="member",
            name="address_additional",
        ),
        migrations.AlterField(
            model_name="member",
            name="address_description",
            field=models.CharField(
                help_text="Example: Via Roma 42/a",
                max_length=200,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="member",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
