# Generated by Django 4.2.5 on 2023-10-05 17:50

import asso.core.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavbarItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Object ordering value",
                        verbose_name="Order",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(blank=True, max_length=50)),
                ("url", models.CharField(default="", max_length=200)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Object ordering value",
                        verbose_name="Order",
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=256, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="object description",
                        verbose_name="Description",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "logo",
                    models.CharField(
                        choices=[
                            ("globe", "Web site (default)"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("x", "X"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "YouTube"),
                            ("github", "GitHub"),
                            ("instagram", "Instagram"),
                        ],
                        default="globe",
                        max_length=24,
                        verbose_name="Logo Icon",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ThemeConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos")),
                ("active", asso.core.fields.UniqueBooleanField(default=False)),
            ],
            options={
                "ordering": ["-active"],
            },
        ),
    ]
